<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- Properties -->

    <!-- Camera -->
    <xacro:property name="camera_offset_x" value="${chassis_length/2}"/>
    <xacro:property name="camera_offset_y" value="0"/>
    <xacro:property name="camera_offset_z" value="${chassis_height/2}"/>
    <xacro:property name="camera_radius" value="0.010"/>
    <xacro:property name="camera_thickness" value="0.03"/>

    <!-- Camera Link -->

    <joint name="camera_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="camera_link"/>
        <origin xyz="0.15 0 0.065" rpy="0 0 0"/>
    </joint>

    <link name="camera_link">
        <visual>
            <origin xyz="${camera_thickness/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${camera_radius}" length="${camera_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
    </link>

    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <link name="camera_link_optical"></link>

    <gazebo reference="camera_link">
        <material>Gazebo/Black</material>

        <sensor name="camera" type="camera">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <topic>camerae</topic>
            <camera>
                <horizontal_fov>1.089</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>8.0</far>
                </clip>
            </camera>
            <plugin filename="ignition-gazebo-sensors-system" name="gz::sim::systems::Sensors"></plugin>
        </sensor>
    </gazebo>

</robot>