<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="properties.xacro" />

    <xacro:property name="laser_offset_z" value="${(chassis_height+laser_thickness)/2}" />
    <xacro:property name="laser_radius" value="0.02" />
    <xacro:property name="laser_thickness" value="0.01" />
    <xacro:property name="laser_mass" value="0.1" />

    <joint name="laser_joint" type="fixed">
        <parent link="chassis_link" />
        <child link="laser_frame" />
        <origin xyz="0 0 ${laser_offset_z}" rpy="0 0 0" />
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_thickness}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_thickness}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${laser_mass}" length="${laser_thickness}"
            radius="${laser_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>

        <sensor name='lidar' type='lidar'>
            <topic>lidar</topic>
            <update_rate>10</update_rate>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>640</samples>
                        <resolution>1</resolution>
                        <min_angle>-1.396263</min_angle>
                        <max_angle>1.396263</max_angle>
                    </horizontal>
                    <vertical>
                        <samples>16</samples>
                        <resolution>1</resolution>
                        <min_angle>-0.261799</min_angle>
                        <max_angle>0.261799</max_angle>
                    </vertical>
                </scan>
                <range>
                    <min>0.08</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>
            </lidar>
            <alwaysOn>1</alwaysOn>
            <visualize>true</visualize>
        </sensor>

    </link>

    <!-- Ignition Gazebo -->
    <gazebo reference="laser_frame">
        <material>Gazebo/Black</material>
        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </ray>
            <plugin filename="ignition-gazebo-sensors-system" name="gz::sim::systems::Sensors">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/msg/LaserScan</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>