<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="properties.xacro" />

    <xacro:property name="laser_offset_z" value="${(chassis_height+laser_thickness)/2}" />
    <xacro:property name="laser_radius" value="0.02" />
    <xacro:property name="laser_thickness" value="0.01" />
    <xacro:property name="laser_mass" value="0.1" />

    <joint name="laser_joint" type="fixed">
        <parent link="chassis_link" />
        <child link="laser_frame" />
        <origin xyz="0 0 ${laser_offset_z}" rpy="0 0 0" />
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_thickness}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_thickness}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${laser_mass}" length="${laser_thickness}"
            radius="${laser_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>

    </link>

    <!-- Ignition Gazebo -->
    <gazebo reference="laser_frame">
        <material>Gazebo/Black</material>
        <sensor name="laser_frame" type="gpu_lidar">
            <pose>0 0 0 0 0 0</pose>
            <topic>scan</topic>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                    <resolution>0.01</resolution>
                </range>
            </lidar>
            <plugin filename="ignition-gazebo-sensors-system" name="gz::sim::systems::Sensors" />
        </sensor>
    </gazebo>

</robot>