<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- Chassis -->
    <xacro:property name="chassis_length" value="0.300"/>                   <!-- 0.800 -->
    <xacro:property name="chassis_width" value="0.200"/>                    <!-- 0.400 -->
    <xacro:property name="chassis_height" value="0.130"/>                   <!-- 0.130 -->
    <xacro:property name="chassis_mass" value="1"/>                       <!-- 0.1 1 -->
    <xacro:property name="chassis_offset_x" value="${chassis_length/2}"/>
    <xacro:property name="chassis_offset_y" value="0"/>
    <xacro:property name="chassis_offset_z" value="${chassis_height/2}"/>

    <!-- Steering -->
    <xacro:property name="steering_radius" value="0.01"/>                   <!-- 0.01 -->
    <xacro:property name="steering_length" value="0.02"/>                   <!-- 0.01 -->
    <xacro:property name="steering_mass" value="0.02"/>
    <xacro:property name="steering_offset_x" value="${(2/3)*chassis_length/2}"/>
    <xacro:property name="steering_offset_y" value="${(chassis_width+steering_length)/2}"/>
    <xacro:property name="steering_offset_z" value="${(2/3)*chassis_height/2}"/> <!-- 0 -->

    <!-- Wheels -->
    <xacro:property name="wheel_radius" value="0.065"/>                     <!-- 0.07 -->
    <xacro:property name="wheel_thickness" value="0.030"/>                  <!-- 0.005 -->
    <xacro:property name="wheel_mass" value="0.3"/>                         <!-- 1 0.3 -->
    <xacro:property name="wheel_offset_z" value="${steering_length+wheel_thickness/2}"/>

</robot>