<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="properties.xacro" />
    <xacro:include filename="materials.xacro" />
    <xacro:include filename="inertial_macros.xacro" />
    <xacro:include filename="robot_macros.xacro" />

    <!-- ================================ Links ================================ -->

    <!-- Base Link -->
    <link name="base_link" />

    <!-- Chasis Link -->
    <link name="chassis_link">
        <visual>
            <origin xyz="0 0 ${chassis_height/2}" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <origin xyz="0 0 ${-chassis_height/2}" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}"
            z="${chassis_height}">
            <origin xyz="0 0 ${-chassis_height/2}" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>
    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- Wheel Links -->
    <xacro:wheel_link prefix="front_left" />
    <xacro:wheel_link prefix="front_right" />
    <xacro:wheel_link prefix="rear_left" />
    <xacro:wheel_link prefix="rear_right" />

    <!-- Steering Links -->
    <link name="front_left_steering_link"/>

    <!-- ================================ Joints ================================ -->

    <!-- Chassis Joint -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis_link" />
        <origin xyz="${chassis_offset_x} ${chassis_offset_y} ${chassis_offset_z}" />
    </joint>

    <!-- Steering Joints -->
    <xacro:steering_joint prefix="front_left" />
    <xacro:steering_joint prefix="front_right" />
    <xacro:steering_joint prefix="rear_left" />
    <xacro:steering_joint prefix="rear_right" />

    <!-- Wheel Joints -->
    <xacro:wheel_joint prefix="front_left" front="1" left="1" />
    <xacro:wheel_joint prefix="front_right" front="1" left="-1" />
    <xacro:wheel_joint prefix="rear_left" front="-1" left="1" />
    <xacro:wheel_joint prefix="rear_right" front="-1" left="-1" />

    <!-- ============================= Transmission ============================= -->

    <transmission name="trans_front_left_wheel_rotate">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="front_left_rotate">
          <hardwareInterface>EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_front_left_wheel">
          <hardwareInterface>EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>

</robot>