<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="properties.xacro" />

    <!-- Steering Link -->
    <xacro:macro name="steering_link" params="prefix">
        <link name="${prefix}_steering_link">
            <visual name="">
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${steering_radius}" length="${steering_length}" />
                </geometry>
                <material name="blue" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${steering_radius}" length="${steering_length}" />
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="${steering_mass}" length="${steering_length}"
                radius="${steering_radius}">
                <origin xyz="0 0 0" rpy="0 0 0" />
            </xacro:inertial_cylinder>
        </link>
        <gazebo reference="${prefix}_steering">
            <material>Gazebo/Blue</material>
            <mu1 value="0.5" />
            <mu2 value="0.5" />
        </gazebo>
    </xacro:macro>

    <!-- Wheel Link -->
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
                </geometry>
                <material name="blue" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}"
                radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0" />
            </xacro:inertial_cylinder>
        </link>
        <gazebo reference="${prefix}_wheel">
            <material>Gazebo/Blue</material>
            <mu1 value="1.0" />
            <mu2 value="1.0" />
        </gazebo>
    </xacro:macro>

    <!-- Steering Joints -->
    <xacro:macro name="steering_joint" params="prefix front left">
        <joint name="${prefix}_steering_joint" type="revolute">
            <origin xyz="${front*steering_offset_x} ${left*steering_offset_y} -${steering_offset_z}"
                rpy="${-1*left*pi/2} 0 0" />
            <parent link="chassis_link" />
            <child link="${prefix}_steering_link" />
            <axis xyz="0 ${-left} 0" />
            <limit lower="-${pi/4}" upper="${pi/4}" effort="1" velocity="100" />
        </joint>
    </xacro:macro>

    <!-- Wheel Joints -->
    <xacro:macro name="wheel_joint" params="prefix left">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <origin xyz="0 0 ${wheel_offset_z}"
                rpy="0 0 0" />
            <parent link="${prefix}_steering_link" />
            <child link="${prefix}_wheel_link" />
            <axis xyz="0 0 ${left}" />
        </joint>
    </xacro:macro>

</robot>

                <!-- <surface>
                    <friction>
                        <ode>
                            <mu>50.000000</mu>
                            <mu2>50.000000</mu2>
                            <fdir1>0.000000 0.000000 0.000000</fdir1>
                            <slip1>0.000000</slip1>
                            <slip2>0.000000</slip2>
                        </ode>
                    </friction>
                    <contact>
                        <ode>
                            <soft_cfm>0.000000</soft_cfm>
                            <soft_erp>0.200000</soft_erp>
                            <kp>1000000000.000000</kp>
                            <kd>1.000000</kd>
                            <max_vel>100.000000</max_vel>
                            <min_depth>0.001000</min_depth>
                        </ode>
                    </contact>
                </surface> -->