controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    fws_controller:
      type: fws_controller/FWSController

fws_controller:
  ros__parameters:
    # reference_timeout: 2.0
    front_steering: true
    open_loop: false
    # velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: true
    rear_wheels_names: ['rear_left_wheel_joint']
    front_wheels_names: ['front_left_steering_joint']

    wheelbase: 0.200
    front_wheel_radius: 0.065
    rear_wheel_radius: 0.065

    # steering_joint_names:
    #   - front_left_steering_joint
    #   - front_right_steering_joint
    #   - rear_left_steering_joint
    #   - rear_right_steering_joint
    # wheel_joint_names:
    #   - front_left_wheel_joint
    #   - front_right_wheel_joint
    #   - rear_left_wheel_joint
    #   - rear_right_wheel_joint
    # command_interfaces:
    #   - position
    #   - velocity
    # state_interfaces:
    #   - position
    #   - velocity