joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      # L UP/DOWN
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular:
      # R LEFT/RIGHT
      yaw: 0
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0

    enable_button: 6
    enable_turbo_button: 7

    require_enable_button: true

# PS4 Controller Buttons

# 0: X
# 1: O
# 2: Triangle
# 3: Square
# 4: L1
# 5: R1
# 6: L2
# 7: R2

# 0: L LEFT/RIGHT
# 1: L UP/DOWN
# 2: L2
# 3: R LEFT/RIGHT
# 4: R UP/DOWN
# 5: R2
# 6: ARROWS LEFT/RIGHT
# 7: ARROWS UP/DOWN