controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    steering_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    wheel_velocity_controller:
      type:  velocity_controllers/JointGroupVelocityController # joint_trajectory_controller/JointTrajectoryController # effort_controllers/JointGroupEffortController

steering_position_controller:
  ros__parameters:
    joints:
      - front_left_steering_joint
      - front_right_steering_joint
      - rear_left_steering_joint
      - rear_right_steering_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    # open_loop_control: false
    # gains:
    #   front_left_steering_joint: {p: 1.0, d:0.0, i: 0.0, i_clamp: 0.0}
    #   front_right_steering_joint: {p: 1.0, d:0.0, i: 0.0, i_clamp: 0.0}
    #   rear_left_steering_joint: {p: 1.0, d:0.0, i: 0.0, i_clamp: 0.0}
    #   rear_right_steering_joint: {p: 1.0, d:0.0, i: 0.0, i_clamp: 0.0}

wheel_velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint
    command_interfaces:
      - velocity # effort
    state_interfaces:
      - position
      - velocity
    # open_loop_control: true
    # gains:
    #   front_left_wheel_joint: {p: 2.0, d: 0.0, i: 1.0, i_clamp: 0.0}
    #   front_right_wheel_joint: {p: 2.0, d: 0.0, i: 1.0, i_clamp: 0.0}
    #   rear_left_wheel_joint: {p: 2.0, d: 0.0, i: 1.0, i_clamp: 0.0}
    #   rear_right_wheel_joint: {p: 2.0, d: 0.0, i: 1.0, i_clamp: 0.0}

# type: effort_controllers/JointGroupEffortController
# type: position_controllers/JointGroupPositionController
# type: velocity_controllers/JointGroupVelocityController
    # pid: {p: 1000.0, i: 0.01, d: 10.0}
    # gains:
    #   front_left_steering_joint: {p: 50.0, i: 1.0, d: 50.0, i_clamp: 1.0}